### ISSUE TITLE
Community Management

### ISSUE THREAD

**Issue by delahee** [HaxeFoundation/Project-Management#12]
Please,

We have to improve a lot on this, please _please_ avoid to close issues about meta subject too fast so that we can discuss how to best respond first if it is possible.

Please also try to process issues hijacking with care: ask to open a new issue about meta sujects rather than group disucssion.

Thanks a lot.

**Comment by ncannasse** [comment]
Refused

**Comment by ncannasse** [comment]
No, I'm joking :)

**Comment by delahee** [comment]
I laughed so loud !

**Comment by Merelleya** [comment]
We should outline community interaction guidelines and best practices internally so as to avoid unnecessarily abrasive behavior. I understand that one can get angry, but in those instances it is often better to take a deep breath and go look at ponies or some such.

I understand that responses could have been worse, but seeing as unfortunately we are always - at least partially - being perceived as speaking for the Foundation, I would like to keep things as polite as possible.

We might also consider a public statement to the community guiding them to the appropriate channels for discussions and convey some points on how best to approach the Foundation and/or relevant topics. As a matter of fact, we really do need a direct, "official" channel.

**Comment by delahee** [comment]
This has many dependencies on the governance model. Let s enqueue this behind.

**Comment by delahee** [comment]
@Jo what would you think of something like getsatisfaction ?

**Comment by Merelleya** [comment]
@delahee I would really appreciate if you could supplement your suggestions with links to appropriate resources, seeing as we do not always enjoy the same context. 

I also do not necessarily agree that a general code of conduct has so many dependencies on what you call "governance". This topic mainly relates to how official representatives of the foundation as well as partners or people who are associated with the foundation should interact with the community so as to minimize the risk of accidental explosions.

so yeah, I can give you a brief outline right now:
- Always observe the general rules of polite conversation
- If you feel too angry to be polite, you should probably not comment yet
- Think about whether what you are writing sends the message you want to send
- Do not dismiss any suggestions without constructive reasoning
- Never talk down to anybody

and so on.

If in doubt, one should probably gather a second opinion, seeing as one does not always see things clearly if one stands too close to the problem

**Comment by delahee** [comment]
@Merelleya hmm ok i 'll go extensive on this one and we'll redact something.

**Comment by delahee** [comment]
On my todo list then ! :)

**Comment by delahee** [comment]
@Merelleya I started gathering ideas, Iwas thinking of three  post : 
- Best practices for contributors
- Best practices for maintainers
- upgrade the "contributing" article.

You ok with this ?

**Comment by delahee** [comment]
Leaving notes here : 
Nice articles about fundamentals : http://thecommunitymanager.com/2013/09/26/how-to-write-effective-community-guidelines/

**Comment by Merelleya** [comment]
I guess we still need community guidelines, so I am taking this back up. @delahee are you still up for this or shall I just put this into my list for now?

**Comment by delahee** [comment]
Yep I'll finalize what I have gathered.

**Comment by delahee** [comment]
adding this https://www.youtube.com/watch?v=-F-3E8pyjFo&feature=youtu.be&a I started something but the result was crappy, I'think i'll do some slides rather than boring text.

**Comment by nadako** [comment]
> adding this https://www.youtube.com/watch?v=-F-3E8pyjFo&feature=youtu.be&a 

Sorry, I'm not following this thread, but I liked that video, especially the part about documenting design decisions, so people can point/be pointed to some issue/post/comment to find out/remember why something was (not) made the way it's done. A couple of months ago I started collecting haxe-related links here https://github.com/nadako/awesome-haxe and it has this `Language design` section. Perhaps we could have a document on haxe.org containing a list of design decisions along with rationale behind them. That way future discussions can be much more reasonable, IMO.

**Comment by Merelleya** [comment]
@nadako that is indeed a very good idea, I will put that on my "to be talked through with the team" list and also open a new issue for it. Other than that I feel that this issue has run its course and would like to close it.

@delahee you ok with that?

**Comment by delahee** [comment]
yeah totally, I wrapped my head a few times around this problem...and the present situation conflict with the current behaviour / response from team members. I am really wondering if prescriptive doc ( vid or not ) would improve the situations and if it would be debated and followed. 

So I think going with nadako's solution for starte would be better, i'll star the repo and add some things here and there on occasion.
