### ISSUE TITLE
Yearly roadmap

### ISSUE THREAD

**Issue by delahee** [HaxeFoundation/Project-Management#14]
We have a big planning issue, for example with the Unicode support etc.. We should plan and prioritize at least for one year in advance. This tasks is dependent on community feedbacks.

**Comment by Simn** [comment]
I'm not sure about this. If we don't address something swiftly it's usually because nobody really has a solution for it. In that context having roadmaps wouldn't do much other than causing stress.

**Comment by ncannasse** [comment]
I agree that we should not only focus at maintaining the compiler but also focus on "bigger advances" in terms of things we're lacking. Unicode often comes on the map, let's do the first steps of the work and then we will hopefully get contributions from community for the next ones.

**Comment by Simn** [comment]
I just don't think adding Unicode to some (redundant) list is going to improve anything. A road map is something _we_ intend work on, not a community contribution request overview. If you want to have that you should call it what it is.

**Comment by ncannasse** [comment]
The goal of a roadmap as I see it is to prevent ourselves from being entirely driven by github issues: we get bug reports, feature suggestions this way, and it's normal and necessary to work on it, but according to my own experience it's sometimes nice to work on "new things" that will bring Haxe to the next level of usability.

Roadmap should be discussed and approved, or I can decide by myself if you prefer. It's fine sometimes to push things to the next release if we didn't have time to work on it and release is getting near, but we should not let go something on the roadmap outside of our radar.

Having roadmap also helps to better communicate with people which are not following [haxedev], as to say "we are working on this".

And yes the goal of the roadmap is to have us working on it, not waiting for the community to come with an implementation. Regarding Unicode, I was actually suggesting that we comes with the first steps, which is IMHO having the String API for various encodings (haxe.Utf8, haxe.Ucs2 at least), as well as review our different classes reading/writing Strings and making them able to accept encoding parameter. I'm hoping the community will then contribute either as library or for inclusion in std, the other parts such as collation.

**Comment by delahee** [comment]
@Simn 
In an ideal world, i would like to tell you "take it easy", missing deadlines and not filling rodmaps is really Ok. I am fairly confident Nicolas will feedback if anything go wrong. So I really like to emphasize how unstressed you should feel, don't put pressure on yourself.

Having a broad roadmap and some kind of hint that we need contributor for those is a first step.

There are many ways to do this for example (fiction here) :

Hf roadmap:

in 6 month:

broad Unicode support with codecs
Analyzer goes default
Xml namespaces
Cpp Debugguer for Fdevelop

in a year months :  
unicode Normalization
Neko Debuggger (;))
UTC Dates

2 year
Money conversions 
UTC timezones

etc and so on.

These are Fictive features of course but either there should have officially supported libs for those either we should have native integration if we want regular app appeal.

If you are not confortable with such timings we can totally discuss all this peacefully here :)

**Comment by Simn** [comment]
Maybe I'm just really scared of Unicode support in particular because to me that looks like a huge mountain that has its peak somewhere in the sky and I don't even know where to start climbing. I'll try to not let that cloud (sorry) my judgement.

**Comment by delahee** [comment]
We trust you Simn, strip your minds roadmap of unicode if need be, we still need this tool ;)

**Comment by ncannasse** [comment]
@Simn re Unicode, it's not that hard to get the basics right

**Comment by larsiusprime** [comment]
One thing to keep in mind is that if we signal we're beginning to work on something, even if it's not huge progress, that really sends a message to the community. For instance, in OpenFL land, we were seriously scratching our heads about what we were going to do about font rendering and layout for the next transition. We put up some issues and plans about getting Freetype / Harfbuzz work, and after a little while of making baby steps there, all of a sudden a nearly-complete implementation comes from a contributor.

Now that's a much smaller task than all of full Unicode support, but I think it demonstrates the example. Start working on something, signal it's important, put out a call for help, and it increases the odds that contributors will help share the load.

(Also -- is it okay and proper for me to post in these threads? I got an invitation to the group, but I don't want to make too many assumptions...)

**Comment by dogles** [comment]
In terms of road map from an outsider's perspective, I think the greatest value will be to give people a simple overview of where Haxe is headed. Right now, I don't have a clear idea of what's definitely planned in the next Haxe release, what's being considered for future releases, etc. 

I know a lot of this is currently in Github issues, but that gets mixed in with bugs and community suggestions. I would love to see something like this:

**Haxe 3.4**
Unicode Support : _DISCUSSION_
Python Target out of Beta : _APPROVED_
Static Analyzer : _IN DEVELOPMENT_

**Haxe 3.5**
LLVM support: _APPROVED_

**Future Proposals**
Graphics std library : _DISCUSSION_

(I'm just making up features here ;)

Some places to take inspiration from:
1. The golang design document is short and sweet, giving people a quick overview of what's been done recently, what's planned in the next release, and what the team is thinking about in the future. https://github.com/golang/go/wiki/DesignDocuments
2. The Python PEPs are a more mature and bureaucratic means of communication/collaboration, with specific style guidelines, an editorial process, and defined stages of development. It's worth thinking about what parts of their process you would find worthwhile and what parts you would want to change, once Haxe is hugely successful and has a massive user base. :) https://www.python.org/dev/peps/pep-0001/

**Comment by Simn** [comment]
I agree this would look really good so sure we can try that. My main concern is that at this point most of the things that haven't been done yet are quite hard to get right in the first place. For instance, I want to make the static analyzer the default for the next release but given Haxe's nature (`Dynamic`, `untyped` etc.) there might just be issues that I do not (yet) have a solution for.

For the same reason I never properly announced that I was working on pattern matching. It was new grounds for me and I implemented it following some research paper. Another example is the DCE-rewrite which I made up as I went.

These are positive examples but there are negative ones too: Any notion of [null-safety](https://github.com/HaxeFoundation/haxe/issues/1306) in Haxe has some challenging problems, smaller features like [build macro in macro](https://github.com/HaxeFoundation/haxe/issues/1798) have some really tricky implementation details and the ambitiously started C-target got stuck due to GC issues.

If either of these would have been on a road map, we likely would have missed them which in turn would have made our road map announcements unreliable. Maybe I'm just lacking self-confidence here, but we'll have to be very careful with what we put on a road map.

**Comment by ncannasse** [comment]
I agree with Simn that we should distinguish the things we're working on / experimenting with, and for which we don't have a roadmap because we don't know how many issues it might raise, from the things we know we will do.

For instance we could have the following:
- Code Analyzer (enable with -D analyzer) : EXPERIMENTING
- Unicode : basic String API support - no collation yet : PLANNED FOR 3.3
  etc.

**Comment by Merelleya** [comment]
So we agree on the following:
- a road-map is nice to have
- we should definitely have one
- we should distinguish between planned features and stuff we are experimenting with so...
- ...we might consider different labels akin to the workflow labels: 
  - PLANNED
  - EXPERIMENTAL
  - APPROVED FOR DEV
  - CURRENTLY IN DEV
  - BEING REVIEWED
  - etc

We should move the discussion to the following issues:
- In what format will this be presented? (A pdf doc, a nice checklist somewhere, pretty diagrams, ...)
- How detailed should it be (will we just give the "headlines" or also some info as to subtasks?)
- Discussion/Approval Workflow
- Who will maintain these

and finally:
- What do we put on it

The last point is a good agenda point for our first team meeting. However, I would like to clear up most or even all the other points beforehand to keep the actual face-to face discussion centered on  the important bits. Also, having the workflow cleared up will ensure that we will actually know what to "do" with our list of road map thingies once we have discussed it.

**Comment by elliott5** [comment]
Great discussion. @Merelleya +1

**Comment by Simn** [comment]
I can't help but think that this maps directly onto github issues:

release - milestone
feature - issue
state - label

I would like to avoid fragmentation so how about this: We mark the relevant feature-issues using some "roadmap" label, then write a small tool using the [GitHub API](https://developer.github.com/v3/issues/#list-issues-for-a-repository) to pull these and publish them nicely somewhere. This way we don't have to maintain lists in several places and can just work like we usually do.

**Comment by elliott5** [comment]
@Simn what a brilliant time-saving idea!

**Comment by Merelleya** [comment]
@Simn has gone off to work on an implementation

**Comment by delahee** [comment]
perfect.
Le 5 juin 2015 14:55, "Josefiene Pertosa" notifications@github.com a
écrit :

**Comment by Simn** [comment]
I've got it to work but there are some SSL issues using it through neko, so I'm not sure how to automate it right now.

**Comment by Simn** [comment]
Here you go: http://haxe.org/community/roadmap.html

The idea is to automatically generate it using this tool: https://github.com/Simn/RoadmapExporter

I can only get this working using PHP and Java locally because SSL on neko/cpp hates me. I thought about just adding it to our travis in some way but I would really prefer a neko-based solution. I'm also not sure how we would pass the access key.

@jasononeil @andyli

**Comment by Merelleya** [comment]
I like!

**Comment by waneck** [comment]
It's looking really good, @Simn ! One niptick: contribute to this page leads to the generated HTML, which is probably not what we want. :)

**Comment by Simn** [comment]
I just realized that we don't want to update it on-commit but on-issue-update, so never mind all that! I'll just run the thing locally I suppose.

**Comment by Merelleya** [comment]
Is this ready to be included into the haxe.org site? Is there something else that needs doing or any additional preparation?

**Comment by Simn** [comment]
I don't know if we want to automate this using a github web hook.

**Comment by ncannasse** [comment]
The roadmap is not complete atm, we need to have a quick meeting to see what are our big next steps

**Comment by delahee** [comment]
@Simn @ncannasse the roadmap should include neko#75 as it impacts the ecosystem deeply, I would also totally be ok for funds to be allocated to its fix.

**Comment by Simn** [comment]
I agree it's important and should be addressed ASAP.

However, we'll have to decide what we want to do with neko in general. It is currently not listed as [supported project](http://haxe.org/foundation/supported-projects.html). Should it?

**Comment by delahee** [comment]
Iny my quality of Fool of the King, Nitpick, Naysayer and Executive Great Goblin Cook, Since Tivo and Mt and other partners have strategic assets, since the Hf host neko on github, since it invades haxe propagation strategy, I now proclaim Neko as a new great ancient and that the Hf should certainly support it. But it's only imvho as usual.

**Comment by ncannasse** [comment]
It should be listed supported project since we support it.
I've to the ELF thing on my (already quite long) TODO list, if someone else want to tackle the issue first, don't hesitate!

**Comment by delahee** [comment]
#friendmode I don't want to make anybody incomfortable, but @simn could you acquire these skills ? My family life do not allow me to get deep into those kind of issues and I cannot allocate MT time for these class of bugs. 
Feel free to rebuke me if you think i am the slightest out of my place, no hard feeling at all. 
Bisous !

**Comment by Simn** [comment]
Frankly, I would prefer not to. I know almost nothing about neko and getting to a state where I could actually help would take me a long time which I would rather spend on other things.

**Comment by delahee** [comment]
@simn ok !

**Comment by kulick** [comment]
Two comments:
1. I want to try to fix this...for ELF anyway, which would help on modern Linux distros.
2. I think that this is important insomuch as it helps us to provide a simpler path to getting Haxe the "normal" way on Linux distros.  We at TiVo don't need this in particular (we build Haxe from source and have a controlled version of neko in our CBE (controlled build environment)).  That said, I think it is a good thing to do to make neko _and_ Haxe easier to use/get on Linux.

I'll review Hugh's link and the neko source and see what I can hack up.  I'll try for tonight (after work and promised dinner w/the wifey...)  ;)

**Comment by kulick** [comment]
Sorry, got confused about which issue I was posting to.  I'll go grab the neko issue that @delahee filed.  :)

**Comment by jasononeil** [comment]
@Simn - finally catching up on everything - this looks great!

What do you want me to help with?  Looks like we need:
- To (preferably) make the exporter tool work with neko.
- Have some kind of server that runs when Github issues are updated.  
  
  Can you get Travis to listen to things other than new commits and pull requests? I don't think it would trigger a build for issue updates... unless @andyli knows a way?
  
  If we get the tool to run in neko I could make it part of the haxe.org repo, and set up a Github webhook to ping the URL when an issue is updated.
- Consider where to display it in the website (which menu), and if there's any CSS changes we want to make.

Let me know what you think the best approach is and I can start looking into it...

**Comment by Simn** [comment]
@jasononeil: We could add a webhook just for issues.

My guess is that the exporter is going to work on neko linux already. I'm attributing the issues I'm having with SSL to the fact that I'm on Windows.

**Comment by markknol** [comment]
I heard Unity now also has a roadmap in case we need inspiration http://unity3d.com/unity/roadmap/

**Comment by delahee** [comment]
I just love that : https://www.nativescript.org/roadmap 
@simn where are we here ? Dya think what we have already can be referenced and outed to the mailing list so we can have feedback ?

**Comment by Simn** [comment]
No

Also: I'm not really interested in public discussions about what should and shouldn't be on our roadmap. That would just end up in an endless drag of arguments that wastes everybody's time and doesn't result in any consensus.

If you feel that something should be on the roadmap, open an issue at HaxeFoundation/haxe. If we (by which I mostly mean Nicolas and me, as well as Hugh/Caue/Andy depending on the target) decide that it should indeed be there we'll tag it accordingly.

**Comment by delahee** [comment]
Yeah sure, its an open source project, people will discuss and want to see
there is a roadmap at some point, at least you might want to plan that it
gets referenced on the website. :)

**Comment by ncannasse** [comment]
I agree with Simon regarding having a lot of people involved in discussing the roadmap, which often ends up in wishful thinking : many "it would be nice if" but not much volunteers to help in these area.

Maybe I will repeat myself again, but I also think that building the roadmap out of issue requests is not good enough. It prevents us from actually having a plan, makes it difficult to prioritize things (since all issues are "equal"), and creates blind spots that can be ignored for far too long (unicode for instance).

So I think we should change our ways of doing. 

For example we could go through a public "request anything" phase, without taking active part in the dicussion/debates that might occur there, then pick what seems both feasible, important, and a good fit for Haxe, and make sure it's being worked on until the next release.

Some of the features/changes might require also some intermediate "testing/experimental" phase, until they can actually be enabled.

**Comment by MatthijsKamstra** [comment]
It seems that there is something of a roadmap, but it's hidden from the public...
Shouldn't it be "activated" in the menu????

**Comment by Merelleya** [comment]
@MatthijsKamstra the implementation shown here was just an example of how it could be done. We are picking this back up and will hopefully arrive at a level of agreement that allows us to show something on the website.

**Comment by Simn** [comment]
So, this is assigned to me but I feel like I've done my part. The rest is a matter of creating/labeling issues that should go on the roadmap.

**Comment by delahee** [comment]
It can be found easily on Google. Fine to me. Congrats!
