### ISSUE TITLE
'Learn Haxe' website

### ISSUE THREAD

**Issue by waneck** [HaxeFoundation/Project-Management#16]
I've been thinking about this for some time now. I'm working on teaching Haxe programming to local communities here in Brazil, and I think that we could use a modified `try haxe` engine to make it easy to write tutorials that can guide on many different matters of Haxe programming. Making it then open to contribution, and having some sort of curation shouldn't consume too much time.

I'm thinking about working on this

**Comment by Merelleya** [comment]
something akin to http://www.codecademy.com/ or the likes?

**Comment by waneck** [comment]
Yes. I think if we put down a roadmap, we could start with just codeacademy's engine - no need of keeping track of progress or anything else.
This could then evolve to include a progress tracking, and even up to something gamified, like http://alexnisnevich.github.io/untrusted/

**Comment by waneck** [comment]
Other reference: https://tour.golang.org/welcome/1

**Comment by nadako** [comment]
http://rustbyexample.com/

**Comment by jasononeil** [comment]
I think rustbyexample.com is my favourite, and would be hopefully quite close to what we have in try.haxe.org, so not too hard to programme.]

It's also high value for low effort in terms of writing new tutorials.  Just need a code example and a quick explanation.

**Comment by mpcref** [comment]
Some more inspiration:
I quite like github's [interactive step-through](https://try.github.io/levels/1/challenges/1) tutorial.

**Comment by Merelleya** [comment]
Anyone wanting to take the lead on this one? Otherwise I will have to see when/how @jasononeil can get to it.

**Comment by waneck** [comment]
I'll take the lead. I'm working on teaching Haxe anyway - and this will come as a big help. I'll first fork try haxe and add a "tour" navigation, or something. We can then create a working group to discuss possible improvements

I plan to get this done by June 22

**Comment by markknol** [comment]
Great, looking forward to it!

**Comment by waneck** [comment]
Update: I've been actively working on it. I ended up not using try-haxe's backend, but instead I'm working on a sandboxed haxe compiler as a service. This means it will support macros, sys targets execution, and more - and being a service, maybe try haxe and others can adapt their code to use those servers instead. Most technical issues are addressed right now, but I'm late in schedule because of that.

@ncannasse, would the HF be interested in financing the servers? Right now I'm thinking on getting a cluster of at least 3 digital ocean VMs (1 for the load balancer, and 2 worker machines) with the minimal settings (that'd be U$15.00/month for all of them). There's also S3 costs, but they should be as low as pratically free. I've designed the servers so they're easy to scale if we need them to - which might happen for example when the learn haxe site goes into the major tech news sites.

**Comment by ncannasse** [comment]
@waneck sure we can pay for it, as long as you promise to maintain them :)

**Comment by waneck** [comment]
Great. I'll maintain it for sure. The solution is coming out pretty nicely also ;)

**Comment by hughsando** [comment]
Any thought of an emscripten version of haxe?  The tech is actually pretty awesome, and all sandboxing and sever costs are borne but the client.

**Comment by waneck** [comment]
That'd be a great idea. I've tried searching, but couldn't find anything about ocaml to emscripten. Maybe we could try js_of_ocaml instead?

**Comment by Khaledgarbaya** [comment]
Hi guys I am starting learnhaxe.org blog
If you are interested in contributing with an article haxe related
feel free to contact me
http://learnhaxe.org/haxe/hello-haxe-world/

**Comment by back2dos** [comment]
@waneck I find js_of_ocaml very interesting, because once this is accomplished
1. Macros can be run as js, rather than on the current interpreter, which will hopefully speed them up quite a bit. Who knows, macro heavy code might even compiler faster than now :D
2. We could generally call from haxe/js output into the compiler and vice-versa. This would open a lot of doors - particularly writing efficient generators in Haxe and even bootstrapping the whole compiler bit by bit.

**Comment by mpcref** [comment]
While were already off-topic... very cool project indeed!
I see big potential here for the Haxe Foundation / Silex Labs to partner up with the Paris-based Ocsigen / PPS / IRILL teams!
From https://ocsigen.org/job

> About Ocsigen:
> 
> Ocsigen is an open source Web development framework, containing, amongst other projects, a compiler from OCaml to JS (Js_of_ocaml) and libraries (Eliom) to develop client server Web applications fully in OCaml, as a single program.
> 
> About PPS:
> 
> PPS is an A-ranked CNRS laboratory of the University Paris Diderot Paris 7. One of its main research topics is the the study of programming languages and distributed systems and their logical foundations. The research activity is associated with an important software development activity, mainly in OCaml (for example Menhir, Unison). The main themes span from the Web (Ocsigen, CDuce, Xduce, Polipo) to parallel programming (Lwt, OcamlP3L, CPC), from networks (Babel) to the management of software packages (Debian, Edos, Mancoosi) and proof assistants (Coq).
> 
> About the IRILL:
> 
> The IRILL is an international research centre on free/open source software located in Paris. IRILL's objective is a reference center for the research and development of stable and reliable free software. IRILL is also an observatory and experimental centre for transfer using free software.

**Comment by markknol** [comment]
@waneck What is the current status of the learn Haxe website?

**Comment by waneck** [comment]
@markknol , the sandboxing is already done at https://github.com/waneck/openjail (and it works quite well). I was working on the compile Haxe API but stopped right now since I've been very busy with my job. I plan to revisit this soon-ish

**Comment by Merelleya** [comment]
@waneck please give us a shout if there is anyone who could help you with anything.

**Comment by Simn** [comment]
This is the typical issue where everyone agrees that it's a good idea but ultimately nothing happens. I'm willing to help with this and provide some content, but somebody else would have to take the lead and I don't see this happening at the moment.

**Comment by Simn** [comment]
We haxe http://code.haxe.org now which works quite well for tutorials.

**Comment by Merelleya** [comment]
@waneck are you still on this?

**Comment by markknol** [comment]
I still hope on something like try.haxe that can integrate in code.haxe.org, that can run macros, have the most popular libraries/frameworks and where code snippets can be run at, but this is not something I can do.

**Comment by waneck** [comment]
@markknol, now that you have code.haxe done, I'll work on this weekend on getting compile haxe to work. It'll support macros and all targets (even though c++/java/c# will be a little harder because of compilation times).
I thought about this last night, and it's pretty close to getting it done if I just use Node.js for handling the calls. I plan to make compile haxe just a REST API that anyone can use - so it won't have a nice interface like try haxe. In fact, I plan to make it a service that try haxe itself could use as its backend

**Comment by markknol** [comment]
Hey @waneck do you have something working already??

**Comment by waneck** [comment]
I did work on it on the weekend, and advanced on its implementation. Sadly I couldn't finish it. Will try to finish it this weekend!

**Comment by Simn** [comment]
I'm getting tired of all these "next weekend" issues, so let's axe it.
