### ISSUE TITLE
Push Issues to [haxe-f] Google Group

### ISSUE THREAD

**Issue by Merelleya** [HaxeFoundation/Project-Management#19]
So,

the idea was to have GitHub automatically push issues to the [haxe-f] google group:

https://groups.google.com/forum/?fromgroups#!forum/haxe-f

However, I can not get it to work properly, which may or may not be due to the fact that the haxe-f group currently is application-only.

Either way, since GitHub sends e-mail notifications, too, I was wondering whether it was really necessary to have it done via the google group. (GitHub itself works like the mailing list, so if you reply to the E-Mail, it will post to the issue on GitHub).

Another problem is that this might duplicate discussion.

Also, from what I can see, the Google Group is not very active.

Opinions?

**Comment by Merelleya** [comment]
please feel free to discuss

**Comment by jasononeil** [comment]
Since I was added to the repository I feel like I'm on a mailing list - email alerts for new issues and comments. So I see no need to get the issues via email too. Unless you want email updates for code submitted too? But it's just a README so I don't think it matters much.

My $0.02

**Comment by Simn** [comment]
I agree, you can just watch this repo if you're interested in what we're plotting.

**Comment by Merelleya** [comment]
I could, of course, just keep adding everybody. But I think it is ok as is.

**Comment by Simn** [comment]
We can use haxe-f for all the secret or bad news such as Nicolas and Hugh getting hit by buses.

**Comment by jasononeil** [comment]
@Simn That made me laugh so loudly I had to explain the joke to people around me.

:person_with_blond_hair: :boy: :bus:

**Comment by dpeek** [comment]
I've started work on a Haxe implementation of both Hugh and Nicolas to deal with these concerns: HxNeko and HxCppHugh.

**Comment by ncannasse** [comment]
Remind me to never cross the street next to Hugh, so we can minimize the risks

**Comment by Merelleya** [comment]
Never mind the risk you incur just by being alive. We really _should_ have AI companions for both of them. Or seriously invest in zombification techniques.

**Comment by dpeek** [comment]
![nicolas](https://cloud.githubusercontent.com/assets/128329/7981470/02655bfe-0aa7-11e5-8bc4-da861c0c0302.png)

**Comment by Merelleya** [comment]
Nicolas' nose is way prettier that _that_

**Comment by hughsando** [comment]
Perhaps you could give me a heads-up if a bus hit is on the road map.

**Comment by Merelleya** [comment]
I suppose this is ready for close, then. Feel free to re-open if you have anything relevant to add to the topic, which can be deduced by parsing the issue-title :P
