### ISSUE TITLE
Meeting with Jason 05/06/2015 - Haxe Web Projects

### ISSUE THREAD

**Issue by Merelleya** [HaxeFoundation/Project-Management#25]
Jason and I just finished our talk about the pending Web Projects for Haxe/The Haxe Foundation. He will do some urgent things as soon as possible and then he will be available for more after the 20th of June. The priorities look as follows:
### Urgent
- finishing up the TiVo article in terms of layout-adjustments
- looking into the recent slowdowns and crashes
- looking into some SEO optimizations (mainly duplicates and getting a sitemap)
- make a small mobile optimization for the side menu in the Haxe manual
### Future in order of Priority
- [Haxe Blog](https://github.com/HaxeFoundation/Project-Management/issues/23)
- [Job/Find Your Developer Platform](https://github.com/HaxeFoundation/Project-Management/issues/6)
- ["Learn Haxe" Site](https://github.com/HaxeFoundation/Project-Management/issues/16)
### Other
- Website for [HaxeDevelop](https://github.com/HaxeFoundation/Project-Management/issues/20) can re-use current current "contribute via GitHub" implementation
- It will not be too much work since it is only an info website with the download
- Same goes for the Neko Website

I will submit the relevant details to the issues already being discussed. The above points may be included in the road-map and I could put them on a Wiki-Page in the meantime?

**Comment by delahee** [comment]
- The "contribute via github" thing when possible is awesome.
- For the "find your developper", maybe we could architecture two aspects:
- Post an a job offer
- Post an a job proposal

and do some basic matchmaking.
The french game site afjv.org made a very nice job of doing that kind of thing.

Just 2 cents.

**Comment by Merelleya** [comment]
Added a Wiki Page with Notes.
