### ISSUE TITLE
Corporate Design Items and Style Guide

### ISSUE THREAD

**Issue by Merelleya** [HaxeFoundation/Project-Management#26]
@markknol has agreed to put some work into some corporate design items. 

I am specifically looking for a version of headed paper in case we want to send around documents and something that can be used for presentations. Also, the facebook page needs a new header and I remember there was a move to unify style across all social platforms.

While we are at it, we might also want to put some thought into a style guide for ease of reference.

Thanks so much for your help, Mark!

---
#### Stuff we want
- [ ] Headed Paper @markknol 
- [x] Presentation/Slide background/design @markknol 
- [x] Style Guide
- [x] Social Media Headers @markknol 
- [ ] Press Page

**Comment by larsiusprime** [comment]
To start with, do we have SVG files or other non-destructed master assets for the Haxe logo and related branding stuff? (Neko, etc).

**Comment by markknol** [comment]
The logo on the website is svg, not sure if there is a neko logo as svg.
Would it be an idea to create a new github repository with all brand assets? Or should they be on the haxe.org website?

**Comment by larsiusprime** [comment]
Why not both? There's lots of times when I've been writing an article and looking for an asset and just have to brave what google image search pops up with, then try to painstakingly remove the white background, etc. Github would be good for SVG... that's ultimately just text data right? And then have a page on the site for media, etc, to easily use.

**Comment by Merelleya** [comment]
My thoughts exactly. We need a press/media page too,

**Comment by markknol** [comment]
Yes it would be great to avoid the google image search, haha i recognize that too. 

Ill think i first start on the headers, because sadly wwx is over. 
I keep forgetting who is responsible for the social media accounts?

**Comment by Simn** [comment]
The girl

**Comment by Merelleya** [comment]
That would be me. Just to be clear, huh?

**Comment by ncannasse** [comment]
While we're at it, maybe we could setup a shop with some branded goods (t shirt, mug, etc.) the goal is not to make benefit here but I'm sure some people would be happy to have them.

**Comment by Merelleya** [comment]
As long as they are pretty....have you seen the game duell haxe-shirts at the con? I was insanely jealous!

**Comment by ncannasse** [comment]
Yes of course we want nice things :) Don't remember the haxe shirts sadly

**Comment by waneck** [comment]
I remember @dpeek had done some t-shirt designs for Haxe which were great!
If anyone has any good ideas, it'd be great to hear them. Perhaps we could ask the community to contribute with designs. I've done some time ago a "Ask me about Haxe" which was inspired by "Ask me about Loom", from Monkey Island: https://twitter.com/cwaneck/status/591870035087519745

**Comment by waneck** [comment]
Here's a reference topic https://groups.google.com/forum/#!msg/haxelang/nGKYxLfo9Ec/O4fkYKV-LscJ

**Comment by alebianco** [comment]
I was thinking of DIY-make some tees like gameduell had (loved their design) for when we start hijacking the local js meetups.
So yeah, the sooner we get officially branded things, the better

**Comment by Merelleya** [comment]
I have included a list of the items mentioned above. Please do speak up if you would like anything else or can take care of a particular item (like the design for the shirts or whatever). 

Game Duell's shirts were black and had the Haxe logo very big on the front. However, the logo was not filled in solid. It was just the outlines in the different orange tones. So there wasn't that instant-bam-orange effect and it looked nice, tidy and geometrical. It was, I think, as subtle as the Haxe logo can be. They also had their own logo on the sleeve. I found them really cool.

**Comment by markknol** [comment]
**Social Media Headers**  Maybe _the girl_ wants to add it to all social media platforms? http://projects.stroep.nl/haxe/social-media.jpg cc @Merelleya

**Comment by Merelleya** [comment]
I can assure you that _the girl_ hasn't the slightest idea what you are talking about xD

**Comment by Merelleya** [comment]
@markknol it comes out rather odd on facebook. would you mind terribly looking into the different sizes required and see how it would fit and look best? 

Thanks a lot!

**Comment by markknol** [comment]
Can you put the header also online for twitter/gplus? You don't have to crop/move it.

**Comment by Merelleya** [comment]
I have taken out the printed items and moved them to #33

**Comment by markknol** [comment]
@Merelleya Can you put the header also online for twitter/gplus? You don't have to crop/move it.

**Comment by Merelleya** [comment]
@ncannasse would you mind doing that? I am having trouble logging in to the haxe_org account again ~.~

**Comment by ncannasse** [comment]
Done on twitter

**Comment by ncannasse** [comment]
BTW we have two twitter accounts : haxe_org for official HF news, and haxelang for Haxe community news. haxelang has more traffic, we should post more often on haxe_org (the roundups for instance), that is, if @Merelleya can actually login into it :)

**Comment by Merelleya** [comment]
I can use it through tweetdeck no problem. We should look into buffer, too, for scheduling.

**Comment by markknol** [comment]
Kind of off-topic but I suggested the Haxe logo for http://svgporn.com/ and now it's there.

**Comment by markknol** [comment]
Is there a Neko logo as SVG available?

**Comment by ncannasse** [comment]
I don't think I have one, it's been made years ago in photoshop

**Comment by MatthijsKamstra** [comment]
Neko logo, perhaps not the original, but the one used on the Haxe website...

http://haxe.org/website-content/pages/img/targets/all-targets.svg

![](http://haxe.org/website-content/pages/img/targets/all-targets.svg)

**Comment by markknol** [comment]
Nicely spotted, great!

**Comment by MatthijsKamstra** [comment]
Don't know if this is the place for it, but I remember a discussion about the Haxe logo and the need for a black "Haxe" logo.
I needed them for the t-shirt design:

http://clients.matthijskamstra.nl/haxe/haxe-logo-negative.svg
![haxe-logo-negative.svg](http://clients.matthijskamstra.nl/haxe/haxe-logo-negative.svg)

http://clients.matthijskamstra.nl/haxe/haxe-logo-vertical-negative.svg
![haxe-logo-vertical-negative.svg](http://clients.matthijskamstra.nl/haxe/haxe-logo-vertical-negative.svg)

_don't know why we don't see a preview_

**Comment by markknol** [comment]
@Merelleya 
I created some demo slides to be used as template for any Haxe related presentation. It has copy/pastable slides with our colors.
https://docs.google.com/presentation/d/1Ax9mZm0-H3rvQ4gRXbtIsh7BNW7NyYVg4y-AK9HJcEk/edit?usp=sharing
Is this useful? It can be downloaded as anything from google drive.

**Comment by MatthijsKamstra** [comment]
@markknol  nice!

**Comment by Merelleya** [comment]
This is lovely!

Am 20/01/2016 um 22:11 schrieb Mark Knol:

**Comment by Simn** [comment]
Can we close this issue or is there anything left to do?

**Comment by ncannasse** [comment]
Ah, I just checked the "black over white" versions of the branding here http://haxe.org/foundation/branding.html , I was thinking at first that I would like to see them changed by filling the HAXE name in black, instead of using only a black outline, but maybe they are better this way actually, any other opinion?

**Comment by Simn** [comment]
I like it the way it is, so I'll close this issue now!
