### ISSUE TITLE
Neko's Roadmap (and debugger)

### ISSUE THREAD

**Issue by fullofcaffeine** [HaxeFoundation/Project-Management#31]
Just linking to the issue I've started at the Neko repo, since I think it makes sense to list it here, too:

https://github.com/HaxeFoundation/neko/issues/74

cc @Merelleya

**Comment by Merelleya** [comment]
Please feel free to comment this into the Roadmap issue #14 , since I think that Simon's solution may work for neko, too. So it might be worth looking into it once there is a plan for neko.

Thank you,

Fiene

**Comment by Simn** [comment]
I guess the main question is what the roadmap _is_, not where/how to display it. But that discussion makes more sense in the neko repository.

**Comment by fullofcaffeine** [comment]
Cool, thank you guys.
