### ISSUE TITLE
Satus of Basis

### ISSUE THREAD

**Issue by fullofcaffeine** [HaxeFoundation/Project-Management#32]
Basis*[0] is listed in the official Haxe website as a feasible framework for building apps for iOS/Android. The problem is that the library doesn't seem to be maintained as of late (last commit is from 2013). Might worth contacting the author and checking its status.

[0] https://github.com/Randonee/Basis

**Comment by ncannasse** [comment]
I don't think this has anything to do here. Please reopen on HaxeFoundation/haxe.org if you think that it's not appropriate to have it listed there.

**Comment by fullofcaffeine** [comment]
Cool, thanks.
