### ISSUE TITLE
Press Release / Communiqué 

### ISSUE THREAD

**Issue by delahee** [HaxeFoundation/Project-Management#36]
I don't want to express opinion for paying for Press Release Sending or Public Relation agent.

But I need Press Release document for haxe 3.2, if you ever meet the press they say,  I am ok to speak about new haxe release, please send me the Pr. And whoops. 

The press need this material, and I need it to communicate and fast forward material to press. 

If it is ok with the team, I can redact and prepare something with presskit() but I won't wait any longer :)

Ok for the team ?

**Comment by Simn** [comment]
Isn't it a bit late to make a press release about 3.2?

**Comment by delahee** [comment]
...we need material, when the first is done, next will be easier and faster to setup, it also needs to be here for Press searching about haxe in Google.  We can totally prepare something for haxe 3.3 but who knows when it will out.

For  a power user or investor or journalist, don't really care about timing, he needs the material. 

We can also issue one for wwx or the gameduell team or whatever event. 

This issue is not about timing but to show the team that there are major communication asset missing for haxe :)

**Comment by Simn** [comment]
I still think you guys overestimate the effect of press releases. From what I've heard they only make sense if you do them on a regular basis, so it's not even very easy to "try it out". Still, I think we should go for a joint TiVo/HF press release first and see if it does anything at all, then reevaluate.

**Comment by delahee** [comment]
Sorry simn if i am not clear. I don't overestimate anythign, i know very well of their small added value, I just "need" some material to communicate with journalist who ask me, it is a fact not an assumption or anything speculative. But it's not a problem if the hf will not endorse them i ll build someting unofficial for my own needs :)

**Comment by ncannasse** [comment]
I think what David needs is a place on haxe.org where we put our PR, and having at least one published. I think it makes sense, and we have better get started early since we will do PR in the near futur anyway, and for this part we don't have to wait TiVo or anybody else :)

**Comment by Merelleya** [comment]
For all website-related stuff we do need to wait for @jasononeil to finish his cross-country move, which should be this week-end. We need to allocate a space in the menu on the website. I think that a "Press" section in the main Menu is ok for now, but we will also have to re-vamp the use-case menu and see where to fit the blog and the showcases and the Manu is sort of cluttered as it is.

@delahee I am happy for you to redact something, since you know best what will fit your needs. I would like to review this before it goes anywhere, though.

**Comment by delahee** [comment]
@Merelleya Perfectly fine ! Thanks !

**Comment by delahee** [comment]
@Merelleya if it s fine,  I'll send a "data.xml" like that is compatible with the doPressKit() format, if one want preempt and install presskit() it's here:  http://dopresskit.com/dopresskit_install.zip

**Comment by Merelleya** [comment]
@delahee s'all good.

**Comment by delahee** [comment]
@Merelleya I wrote a first draft but we should have a disucssion about tone. I love how american companies keep a lighthearted tone and I often feen the Hf is a little bit..."abrupt" in its communication... so can you send me contact post me an email where I can send you my drafts link ?  Thanks !

**Comment by Merelleya** [comment]
send it to Fiene@haxe...

**Comment by delahee** [comment]
sent on two different mails, I guess your on holidays ;)

**Comment by delahee** [comment]
Well been a while :) 

Since i haven't had feedback, here is the doPresskit template I have modified : https://www.dropbox.com/sh/wgheyvnvex184u2/AABe1hGBVcihjISNtAfr3cmga?dl=0

I can totally re-redact if the tone is not good. ping me if you want an updated version for next haxe release, I'll gently close the topic if hf is not interested :)

cc @ncannasse @andyli

**Comment by MatthijsKamstra** [comment]
:+1:

**Comment by delahee** [comment]
Never got any team feedback.
