### ISSUE TITLE
LinkedIn group for <your country here>

### ISSUE THREAD

**Issue by mpcref** [HaxeFoundation/Project-Management#37]
Hi,

I've just created a [group on LinkedIn for Dutch Haxe Developers](https://www.linkedin.com/grp/home?gid=8333349) after seeing [a question in the Haxe Google Group](https://groups.google.com/forum/?hl=en#!topic/haxelang/jILHdFET4sg) about a Haxe job offering in The Netherlands.

I guess there should be some governance over groups like these as well?
Is there any readily available material I should/could use for this LinkedIn group?
What about the idea of starting LinkedIn groups for each country where there's active Haxe developers?
We could invite people on the mailing list to start or join these groups for their country.

**Comment by delahee** [comment]
Nice idea ! Could you coordinate the linkedin efforts ? There is already a heavy load on the benevols we can defenitely use a hand ! :D

**Comment by Merelleya** [comment]
@cref I would be very happy to get some help with this. How is the LinkedIn group going, anyway? 

If you think this would be useful, we could put out a call on the mailing list, asking people to make groups. In general, though, its getting harder and harder to stay on top of all the groups on all the networks, so this would be something that I would encourage the community to do, but would not want to have to look after too much.

**Comment by andyli** [comment]
I just think of the Haxe user map that appeared years ago and I still think that is interesting to look at => https://www.google.com/maps/d/viewer?mid=zNXUFQfJmbJw.kJWU4eCTbrw0&hl=en_US

Maybe we can display the list of Haxe user group in such a map... Well, when we have a least a few user groups.

**Comment by mpcref** [comment]
There's not a whole lot of members (10 at the moment) but that was to be expected as there aren't that many Dutch Haxe developers. At least there is now a place where Haxe-related jobs in The Netherlands can be posted (none for now). I was just wondering whether we should adopt certain guidelines for these LinkedIn groups?

**Comment by MatthijsKamstra** [comment]
@andyli I like the map also, a friendly way of showing the "secret society of Haxe" :smirk: 
Perhaps add it to the website (this is the first time I see it...)???
