### ISSUE TITLE
Seeking contributors to learnhaxe.org Website

### ISSUE THREAD

**Issue by Khaledgarbaya** [HaxeFoundation/Project-Management#38]
Hi guys I am starting http://learnhaxe.org blog/website and I am looking for contributors to write articles there, it could be about haxe in generale or a specific technology done on top of haxe.
My Aim is to have an article every week or 2 weeks but I can't do that by my own, so if you feel like you want to share your haxe experience contact me.
Best,
Khaled

**Comment by Simn** [comment]
It's a valiant effort but don't expect anyone to jump on board until you have at least provided some ground work.

**Comment by ibilon** [comment]
Slightly off topic, but before starting to write brand new articles about haxe wouldn't it be useful and less redundant to have a links to all these already existing articles?

Like for instance learnhaxe.org doesn't really need to write an article on hxml, there's already a couple scattered on the internet: http://matttuttle.com/2015/06/hxml-overview/, http://blog.onthewings.net/2013/03/04/hxml-tricks-every-haxe-user-should-know/

Also an import point in my opinion: a collection of articles/tutorials is only useful if the articles are tagged, searchable and easy to find.

**Comment by Khaledgarbaya** [comment]
@Simn I agree with you, I still have a lot of work to do with the website like completing all the sections and writing more articles. I wanted to the share the website for people to keep in mind 
@ibilon you are right I'll do my best keeping the informations in the website well structured and SEO friendly, Also I'll try to avoid redundant content as much as I can

**Comment by markknol** [comment]
While I think more tutorials and content is always good (:smile:), I rather have every good writer on board to join the Haxe manual + tutorial team. We are planning to have a community driven tutorial section on the site. Would you be interested in helping on this too? It would save you time to build, manage and maintain the website.
