### ISSUE TITLE
launchpad account

### ISSUE THREAD

**Issue by andyli** [HaxeFoundation/Project-Management#41]
I've created a [launchpad account](https://launchpad.net/~haxe) to host a Ubuntu PPA.

It would be better to have a few more members there (@ncannasse, @Simn, @waneck ?). Just in case I'm not available (hopefully never) but you want to make a release or update something. Please let me know your launchpad account id and I will add you there.

I will document how to build and upload packages soon.

**Comment by clemos** [comment]
That looks great !
I have no particular knowledge in building deb package, or in launchpad, but I'd be happy to help.
My account id is cl3mos.

**Comment by Merelleya** [comment]
@ncannasse, @Simn, @waneck please comment

**Comment by waneck** [comment]
Woohooo! That's great news!
I'd be happy to join. I'll create an account tonight and post here. Thanks, @andyli for all of your hard work! :)

**Comment by ncannasse** [comment]
I'll leave @andyli and @waneck handle it, since I have no launchpad account, I might not be able to help even in case there is some issue :)

**Comment by waneck** [comment]
@andyli , you can add me if you'd like. My user name is `waneck`

**Comment by andyli** [comment]
I've added @clemos and @waneck right now. ;)
Anyone who want to be added just let me know.
I'm closing this issue for now.
