### ISSUE TITLE
Propagating the medium post about the CEO search

### ISSUE THREAD

**Issue by delahee** [HaxeFoundation/Project-Management#45]
Hi folks,

I suggest we try to help Nicolas by propagating ( https://medium.com/@ncannasse/some-words-about-haxe-foundation-e97a4e9d7e41#.z6p38pooo )

@larsiusprime Do you think you can have something set up in gamasutra or am I off topic ? I believe you already know slashdot & reddit and had success at some point ? I can help to redact something but I Haven't got much points
@Merelleya @kulick any idea on which medium we could put strength to have the content visible ?
@damoebius I recall you had success with linuxfr, could you make up something ?

I'll try with hackernews, if i can get something.

Thanks !

**Comment by damoebius** [comment]
I'll 

Le 24.11.2015 17:29, delahee a écrit : 

> Hi folks, 
> 
> I suggest we try to help Nicolas by propagating ( https://medium.com/@ncannasse/some-words-about-haxe-foundation-e97a4e9d7e41#.z6p38pooo ) 
> 
> @larsiusprime [1] Do you think you can have something set up in gamasutra or am I off topic ? I believe you already know slashdot & reddit and had success at some point ? I can help to redact something but I Haven't got much points
> @Merelleya [2] @kulick [3] any idea on which medium we could put strength to have the content visible ?
> @damoebius [4] I recall you had success with linuxfr, could you make up something ? 
> 
> I'll try with hackernews, if i can get something. 
> 
> Thanks ! 
> 
> ## 
> 
> Reply to this email directly or view it on GitHub [5].

## Links:

[1] https://github.com/larsiusprime
[2] https://github.com/Merelleya
[3] https://github.com/kulick
[4] https://github.com/damoebius
[5] https://github.com/HaxeFoundation/Project-Management/issues/45

**Comment by delahee** [comment]
I did something for slashdot : http://slashdot.org/submission/5276749/haxe-foundation-is-looking-for-a-new-ceo

and hackernews is done too : https://news.ycombinator.com/newest ( or here more probably because its already buried https://news.ycombinator.com/submitted?id=blackmagic )

I'll wait for Lars' input to see something about reddit.

**Comment by damoebius** [comment]
Job Done : 
http://linuxfr.org/news/la-haxe-foundation-recrute-son-ceo

Anyone can post something on LinkedIn ?

**Comment by delahee** [comment]
S'okay, Nico did.
