### ISSUE TITLE
Haxe Resource

### ISSUE THREAD

**Issue by tiagolr** [HaxeFoundation/Project-Management#46]
Hi, I've been working on this wonderful site to aggregate learning materials such as articles and tutorials related to haxe programming language.

[http://haxeresource.meteor.com](http://haxeresource.meteor.com)

It's almost ready at this stage, and so far it had little or no problems during production.

I'd like to ask you if at some point it can be transfered to the HaxeFoundation servers, and possibly make it an official haxefoundation asset (even if at a later stage), I would like to see it happen for a couple of reasons:
- **Faster loading times** - meteor free servers are slow and some times do not respond at all
- **Indexed search** - meteor servers do not allow database indexed search, and the app gets 10x better with that feature.
- **More visibility and credibility** - making it official comes with that perk
- **Haxe improvement** - haxe users can benefit from a central information site

Haxeresource is built with haxe and meteorjs, I never hosted a meteor application myself, but i guess it only needs: **nodejs** and **mongodb** installed.

I'd be happy to maintain and keep adding contents to this application (I quite enjoy it), currently I have a big list of tutorials to add and a list of features to implement, I work on them as time and motivation permits.

Thank you,

**Comment by ncannasse** [comment]
Hi and thank you for this website.

It looks like I could indeed become some valuable website for haxe resources.

One thing I would like to see added before we host it would be a way for users to easily submit links, while still having you manually confirming them for inclusion. That could be as easy as a "Submit Link" button/form that could be on each page.

After that we could ask the community to submit links to fill the database. This way when we make it official there will be already much more content that there is right now, which would have a greater impact.

**Comment by larsiusprime** [comment]
This could be really amazing and I would love to see this officially adopted by HF.

**Comment by tiagolr** [comment]
Thanks, @ncannasse I'll see into that. At the moment there are lots and lots of contents to be added, one question, would the submit link require login? The advantage of requiring login is that the link can be attributed to that person and also avoid spamming, on the other hand it's always a bit more discouraging to have to login. Anyway I'll make it require login first, then remove it if needed.

**Comment by larsiusprime** [comment]
Maybe enable something that lets you login with Facebook, Google, Github, Twitter id's via OAUTH in addition to traditional login? Then you have login tied to identity but friction is less.

**Comment by tiagolr** [comment]
It does since quite some time now: facebook, github and google i think.

**Comment by ncannasse** [comment]
I think that no login is better, you can still add login once you get too much spam, at this point the database should be quite big already

**Comment by Merelleya** [comment]
Hey @tiagolr,

This looks really amazing. Please let me know if you need help with anything from our side!

**Comment by Simn** [comment]
Is this still a thing? The original website doesn't seem to exist anymore.

**Comment by RafaelOliveira** [comment]
this website had a functionality of add links to tutorials and articles from external websites, could this be implemented in http://code.haxe.org? with a sign indicating that is a link of a external website. Or it is outside the scope of code.haxe.org?

**Comment by Merelleya** [comment]
The project is more or less dead for now. I don't think we have the resources (time-wise) to actually maintain this at the moment.

**Comment by markknol** [comment]
do we still have the database/links ?

**Comment by Merelleya** [comment]
Tiago answered this on the Newsgroup:

> Hey Josefiene thank you for noticing.
> 
> Meteor has canceled the free hosting service they provided a couple of days ago, I've backed up the database but I haven't re-hosted the application so far.
> 
> I've been very busy, and I haven't decided if I declare it "dead", if i host it with a bought domain (I actually own a small production server), or if I host it as a demo application with ip url only (i showcase that application many times for interviews, clients etc..).
> 
> So far my plan is to declare the project dead, open source the database backup and host the app for showcasing without a bought domain.
> 
> Let me know if you want to use it for the haxe community, personally that would be ideal tho maybe it's not the most needed effort.
> 
> Cheers,
> 
> TiagoLr

I liked the database quite a bit. It would satisfy the request to collect articles and videos and resources in one place. This has been asked for several times by the community. The only concern I have is the maintenance, since the DB will only be good if people keep adding their resources, tag them correctly, etc.

**Comment by tiagolr** [comment]
Agree with @Merelleya, I'll upload the database backup soon, I'll probably also host the project for showcasing, I think it's a very cool app but it's not that "much needed" since there are many documentation solutions that work well for different project / communities.

Anyway I'll post when I put it online, If there is interest in keeping this project going I'm interested in keeping it of course (or I wouldn't start it in the first place), one thing I do like doing is categorizing information but myself included did not use this site very much.

Also thank you for the support and liking the idea, that's always great!

**Comment by markknol** [comment]
I dont think we will receive the database. Lets close it.
