### ISSUE TITLE
server maintenance

### ISSUE THREAD

**Issue by andyli** [HaxeFoundation/Project-Management#51]
I plan to do some server maintenance in the next week.
In the mean time, the haxe.org website, lib.haxe.org, and haxelib install will be unavailable.
The tasks include backup, reseting MySQL root password, and creating new MySQL accounts for remote connection.
I want to proceed as careful as possible, and don't want to lose any precious data along the way. 
I will make an announcement of this when the date/time is finalized.

@Merelleya Would you take a look at the Google Analytics data to find out when do we have the least traffic for haxe.org and haxelib? I suspect Sunday would be the best, but I want to confirm. It would be great if you can give me a time period.

**Comment by Merelleya** [comment]
Hey Andi,

the night from Friday to Saturday or Saturday to Sunday are lowest in traffic (considering CET times). So I think for your timezone Saturday or Sunday morning is the best time to do the maintenance. Let me know when you want to do it and I will send a quick tweet to #Haxe before we do so people don't get nervous.

**Comment by andyli** [comment]
Thanks!
I will do the maintenance from 2016-03-20 03:00 UTC+1 to 2016-03-20 06:00 UTC+1.
I will post a notice to the haxe mailing list and you may tweet that post.

**Comment by Merelleya** [comment]
Very good!

Am 14/03/2016 um 12:33 schrieb Andy Li:

**Comment by andyli** [comment]
I've posted at https://groups.google.com/forum/#!topic/haxelang/S1hm8BUGfw4

**Comment by andyli** [comment]
It's done : )
