### ISSUE TITLE
Release frequency

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/Project-Management#52]
### To update or not to update

I think it is a dilemma for many Haxe users that there is a desire to update to latest version of Haxe, because that will fix some bugs which appears in stable version. However, updating will very likely bring you some other bugs or even breaking changes.

This problem is basically caused by a single development branch model used by Haxe, that bugfixes are mixed with new features in the same branch. 
### Proposal

I would like to see Haxe use the ["git flow" model](http://nvie.com/posts/a-successful-git-branching-model/) (TL;DR; see below for a quick summary), which clearly separates "new feature", "hotfixes", "releases" branches. 

As a result, bugfixes can be merged into the master branch more quickly and cleanly without mixing with in-development / non-well-tested features.
### Quick summary about Git Flow Model

2 main branches
- development: A stable branch in development
- master: A stable branch released to public

other branches
- feature: new feature are developed in this branch and merge back to development when complete
- hotfix: immediate bug fixes for master branch
- release: diverge from development, no new feature will be added, after fixing all bugs then will be merged to master

**Comment by Simn** [comment]
We're all terrible with git and changing our workflow to anything more complicated than what we have now would only cause us a lot of grief and anger.

Regarding release frequency, we tried going for a 6-month release cycle but there are so many people involved that it's not very easy to do this reliably. Also, making releases is actually quite a bit of work so unless someone wants to step up and become our release manager I don't think we're going to see (m)any changes.

**Comment by kevinresol** [comment]
@Simn I assume you guys are using SourceTree (it is the most popular) which has built-in support for the Git Flow model. It is not at all complicated to use since SourceTree will handle all the merging/branching for you. You just have to decide where your commit should go (hotfix or new feature, etc) and click the correct button.

Edit: added a brief summary for the model and hope that it convince you it is not that complicated as you think.

**Comment by Simn** [comment]
Let's say I make a release branch for 3.3.0-rc and we start bugfixing on it. Then Hugh forget about it and pushes some hxcpp bugfix commits to development because that's what he does. Now what? I might notice it, in which case I have to manually cherry-pick these commits onto the release branch, or I might not, in which case the release branch doesn't have the fixes.

I agree it sounds nice in theory, but I don't think it would work for us in practice.

Also please note that in our case most of the breaking changes come from bugfixes, not new features. When it comes to compilers new features are often orthogonal and/or optional, so this really wouldn't help much with your original problem.

**Comment by kevinresol** [comment]
I understand your concern. But it is all about balancing the cost and benefit.

I would also like to point out that there are bugs in 3.2.1 that get fixed and are not related to 3.3 at all (e.g. see all those php bugs or those std lib enhancements). At the end I would just like to raise the awareness that mixing all the "sure bug fixes", "experimental bug fixes", "non-tested new features" in a single branch is definitely not a good idea.

But still, I truly understand that all these things require a release manager to make decisions.
