### ISSUE TITLE
Docker image for Haxe

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/Project-Management#55]
Will HF officially maintain a Docker image of Haxe?
I would use that for GitLab's CI

**Comment by andyli** [comment]
I looked at it and planned to do so. It is just I'm too busy right now.

**Comment by anissen** [comment]
There are [some existing repositories](https://github.com/search?utf8=%E2%9C%93&q=haxe+docker) with docker images for Haxe that might be used as a stepping stone for creating an official image.

**Comment by andyli** [comment]
I knew there exist many such images. They do work for the creators' purposes, but they wouldn't be suitable to be one of the [official images](https://github.com/docker-library/official-images) since they don't follow the [best practices](https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/) strictly.

**Comment by kevinresol** [comment]
I created a pure haxe 3.3.0-rc.1 + neko 2.1.0 image [here](https://github.com/kevinresol/docker-haxe/blob/master/Dockerfile)

Can be used as [`kevinresol/haxe:3.3.0-rc.1`](https://hub.docker.com/r/kevinresol/haxe/)

@andyli feel free to take it if needed

**Comment by back2dos** [comment]
Awesome :)

**Comment by kevinresol** [comment]
I created an [autobuild docker repo](https://hub.docker.com/r/kevinresol/haxe/tags/) that can build against lastest haxe commit
But it needs to get notified when a new haxe push happens (with some webhook)
Maybe someone in the foundation can help me? 

But I still think it should be made "official"

**Comment by andyli** [comment]
Done :) https://hub.docker.com/_/haxe/
