### ISSUE TITLE
typo in the heaps streaming blog post

### ISSUE THREAD

**Issue by npretto** [HaxeFoundation/Project-Management#56]
http://haxe.org/blog/nicolas-about-haxe-episode-2

> hxd - takes care of cross platform events, formats an**_s_**d resources

(i didn't know where to submit this, hopefully this is ok)

**Comment by markknol** [comment]
It is updated. Thanks!

**Comment by npretto** [comment]
oh, just noticed that "Playstation" is spelled "Paystation" too :P

**Comment by markknol** [comment]
done
