### ISSUE TITLE
Publish Neko release

### ISSUE THREAD

**Issue by markknol** [HaxeFoundation/Project-Management#57]
I think we need to publish the Neko release through all social channels and the blog. 

cc @andyli @Merelleya

**Comment by andyli** [comment]
I didn't announce it because I thought we can do it together with the release of Haxe 3.3. But since Haxe 3.3 is delayed, we may announce Neko 2.1 first.

**Comment by markknol** [comment]
Is this mentioned somewhere already?

**Comment by markknol** [comment]
I think its too late to do something with this.
