### ISSUE TITLE
Local Meet Up and Street Teams

### ISSUE THREAD

**Issue by delahee** [HaxeFoundation/Project-Management#9]
We should centralize a list of meet ups.
We might want to design street team package (shirts, stickers, usb key loaded with haxe) , like haxe briefs, possible master classes, concrete can change ways to develop.

Our priority should be the valley, nyc, london.

**Comment by larsiusprime** [comment]
I'm closest to Houston and Austin in Texas. Austin is traditionally a pretty big tech hub, a leader in the whole country, and isn't super far away; Houston is a huge city (one of the largest in all of USA) but has a sparse tech community at best.

**Comment by kulick** [comment]
I am currently meetup.com owner of the Haxe group in the Bay Area.  I follow in Justin Donaldson's footsteps on this.  We have done three or four events, one here at TiVo.  Turn out has varied from 10 people to 25 people.  Still growing the community.

I would welcome advice or, even better, prepackaged content that might make a good meetup topic.

**Comment by kulick** [comment]
Reading this got me off my butt and I kicked off a thread about having another meetup later this month...  :)

**Comment by Merelleya** [comment]
So you think it would be cool if we prepared Haxe-Lessons or some sort of content-package with ready-made presentations or Lessons that you could then hold at the meetups?

I think this is a nice idea, we would have to think about the format, though. I remember there was an initiative to get maths teachers to teach more programming last year, and you could get ready-made lessons with activities and everything. I loved that.

**Comment by lucamezzalira** [comment]
Hi All

I started to talk with Philippe Elsass to organise a meetup about Haxe in my JS community (http://www.meetup.com/London-JavaScript-Community/) in London.
I'd like to involve also David from Massive Interactive and someone from Gamesys, that recently moved to Haxe for some of their games, in order to do 3 talks in the same event showing the platform and trying to explain why they should give a try.
Recently I read an article on Babel that could be a good hook to grab the attention of the JS developers because it's an hot topic (at least in London :D), check out the paragraph "Babel: the platform" : http://codemix.com/blog/why-babel-matters?utm_source=javascriptweekly&utm_medium=email do you find any similarity with Haxe ?! :D

**Comment by bablukid** [comment]
After the WWX, I registred on meetup.com on PHP and JS groups and I'll introduce haxe in these groups in Bordeaux and Paris as soon as possible.

I also got some plans of contaminating digital artists, since we can now use haxe for Processing and OpenFrameworks

**Comment by kulick** [comment]
@Merelleya: Yeah.  We would need to think about the format and audience some though.  Haxe appeals to such a broad array of people for a broader array of reasons.  Regarding format, most of our meet ups have been very informal, just people and space for talking (no projectors, audio, private space, etc.) so complicated lessons (like the excellent macronauts talk on WWX workshop day) would require some different, more structured location planning by me.

I think that this means that there are some different possibilities for how to run a meetup, but we need to think through what would actually attract interest and grow the community.  I'll definitely make this topic an informal discussion of the meetup that I'm planning later this month to get some input from actual meetup attendees...

@lucamezzalira & @bablukid : go guys, go!  ;)

**Comment by MatthijsKamstra** [comment]
A good idea would be to collect all those talks (and presentations) in one place, so future talks could benefit from them.

**Comment by Merelleya** [comment]
@MatthijsKamstra that is indeed a good idea and something we should include on our website as well. While we might not collect all the content there is, I think it would be good to have links to the talks or rather to the places where the talks can be found (e.g. The Silex Labs YT account and so on)

 Thank you for the suggestion!

**Comment by lucamezzalira** [comment]
Hi All
today I had Andy Li as speaker on my London meetup, you can find the recording here: https://www.youtube.com/watch?v=7YNR9HAm6D0 (300ish people watched the video :D )
I'm trying to organise a second webinar with Philippe Elsass in order to have something more in deep always for JS devs

**Comment by Simn** [comment]
I'm closing this issue because I don't see anything actionable here. The video part can be handled in #42.
